server:
  port: 8081
spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:mysql://localhost:3306/cs_course_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "00000712"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848     # 本地访问 Nacos
        heart-beat-interval: 5000       # 5 秒发心跳
        heart-beat-timeout: 20000       # 20 秒无响应视为挂了
        health-check-url: /actuator/health
        ephemeral: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
