server:
  port: 8081

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:mysql://coursehub-mysql:3306/cs_course_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 00000712

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        # 🟢 开启心跳机制（客户端 -> Nacos）
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        # 🟢 开启健康检查（Nacos -> 服务）
        health-check-url: /actuator/health
        # 服务实例的IP和端口，会自动注入
        # ip:  # 不配置则使用容器IP
        # port:

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
