#spring.application.name=course
#spring.datasource.url=jdbc:mysql://localhost:3306/cs_course_db?useSSL=false&serverTimezone=Asia/Shanghai
#spring.datasource.username=root
#spring.datasource.password=00000712
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
