#server:
#  port: 8081
#
#spring:
#  application:
#    name: course
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/cs_course_db?useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: "00000712"
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  h2:
#    console:
#      enabled: false
spring:
  profiles:
    active: local   # 或 docker，启动时可以覆盖


